### ISSUE TITLE
Is it works?

### ISSUE THREAD

**Issue by cainrus** [Stevenic/self-instruct#1]
Hello, Stevenic!
Got your repository from https://community.openai.com/t/dissecting-auto-gpts-prompt/163892/15
Does it work or in progress?
I see missing root tsconfig.json and `tsc -b` command fails, due to bad types.

**Comment by Stevenic** [comment]
Hey @cainrus... My employer, Microsoft, requested I move the code to a private repo during development. I've deleted the code that's out there (really old incomplete code) to avoid any confusion. I'll have more I can share in a few weeks.
